acsone/git-aggregator

README.rst, git_aggregator/config.py, git_aggregator/repo.py, git_aggregator/utils.py, tests/test_config.py, tests/test_repo.py
With this simple patch, we will save lots of time, disk space and bandwidth by default, by only fetching required remotes. In projects like Odoo, this means saving thousands of commits between versions.
@Tecnativa
=> Fetch only required remotes. Saves disk space and bandwidth by default.

README.rst, git_aggregator/config.py, git_aggregator/main.py, tests/test_config.py
* Add optional environment variable expansion for the config file
=> [IMP] Expand env vars in config

git_aggregator/main.py, git_aggregator/repo.py, setup.py
you need to have GITHUB_TOKEN in your environment to avoid github api rate limits
=> add a command to show github pull requests that are not open

README.rst
Current result w/ README example:
```
expected <block end>, but found '<block mapping start>'
in "<string>", line 43, column 5:
shell_command_after:
^
```
This is fixed and I added an example on how to apply a patch (just tested w/ latest odoo sec patch).
=> shell_command_after: fix doc and add real life example

README.rst, git_aggregator/config.py
Since file handler name is being provided directly to `Kaptan` instance, it doesn't try to guess it. Although, it is able to do pretty much the same job of taking the extension from a filename and then using an appropriate file handler to parse stuff - you don't need to be so explicit here :)
As a fancy side-effect - for me, git-aggregator has finally started to parse `.yml` files properly. I'm aware that there's #14 in a `master` already, but that approach doesn't really solve the issue outside of the autocompletion scope.
Kaptan tries to guess the handler [here](https://github.com/emre/kaptan/blob/8f5406517a3eca2f473cea3028ff4ddbdf917fbd/kaptan/__init__.py#L70-L75)
Currently, providing a `handler='yml'` handler directly ends up in a `KeyError` …
=> Let Kaptan pick the handler of it's own choice

git_aggregator/log.py, git_aggregator/main.py, git_aggregator/repo.py, git_aggregator/utils.py, tests/test_log.py, tests/test_repo.py
(Cont. from https://github.com/acsone/git-aggregator/pull/16)
**[REF]** Use `cwd` in system calls instead of the `WorkingDirectoryKeeper`, changing the process CWD is not thread-safe as it is shared among all threads.
**[REF]** `multithreading` + `queue` instead of a `multiprocessing.Pool`: better I/O operations, better `Exception`s management, prevent logs from getting messed up...
**[IMP]** Show current repository name in logs (useful when using multiple threads).
**[FIX]** Log date was using `%m` (zero-padded month) instead of `%M` (zero-padded minutes).
**[REF]** Rename `--pool-count` to `-j`/`--jobs`, to mimic `git fetch` params.
**[ADD]** Multithreading tests.
=> [IMP] Add multithreading option for aggregation (cont.)

README.rst, git_aggregator/repo.py
Before this patch, an URL with `/pulls/` appeared in the logs, when the correct one is with `/pull/` instead.
It turns out the GitHub API returns the browsable URL in the response, so I use that one instead.
Also, bots tend to mark PRs as closed instead of merged, but add some label that indicates such state. Let's log labels to have that information at hand.
=> Fix wrong PR URL in logs and log closed PR labels

git_aggregator/repo.py
I don't see any good reason not to add full info here.
=> collect_prs_info: include full data

README.rst, git_aggregator/config.py, git_aggregator/main.py, tests/test_config.py, tests/test_repo.py
This PR extends the variables substitution in the config file allowing to specify additional variables in a file. The variables from the file are with lesser priority than the environment variables. 
The feature is useful in a docker-compose context for example where the local user configuration can be extracted in a .env file. 
A more flexible implementation may be done by using the python-dotenv package but I preferred not to add additional dependencies for such a small feature.
=> [IMP] Get env variables from file

git_aggregator/main.py
`gitaggregate` catches `KeyboardInterrupt`, I'm guessing to avoid an ugly traceback.
But we run `gitaggregate` in a shell script (with `set -e`), and interrupting it should also stop the script. That only works if it exits with an error code.
=> Do not exit with success on KeyboardInterrupt

README.rst, git_aggregator/config.py, git_aggregator/repo.py, tests/test_config.py, tests/test_repo.py
This makes it possible to use the `target` configuration without a remote (in which case pushing will be impossible) and to leave it out completely (in which case a branch called `_git_aggregated` will be used for aggregation).
Resolves #30.
=> Make the `target` section optional

README.rst, git_aggregator/repo.py
Remote remote odoo <https://gitlab.example.com/odoo/odoo.git> -> <https://github.com/odoo/odoo.git>
becomes
Updating remote odoo <https://gitlab.example.com/odoo/odoo.git> -> <https://github.com/odoo/odoo.git>
Info @wt-io-it
=> Change log message for updating remotes

git_aggregator/repo.py
avoid errors when git is configured with `pull.ff = only`.
=> ensure non-fast-forward merges

git_aggregator/repo.py
Closes https://github.com/acsone/git-aggregator/issues/45
As mentioned in the issue discussion, the aggregation process could be improved to start with a `git clone` instead of a `init` followed by `fetch`. This PR implements that.
That also opens the possibility to use `git-autoshare` to speed up the process and save space. This PR also adds that functionality, whilst keeping the original setup working when you don't have `git-autoshare` installed in your system.
@Tecnativa
TT32042
ping @sbidoul @Yajo
=> Clone repo instead of init + fetch and take advantage of git-autoshare

git_aggregator/repo.py
ensure default pull fast-forward behavior is used to avoid errors when git is configured to use another behavior through the `pull.ff` option.
replaces #65.
=> ensure default pull fast-forward behavior

README.rst, git_aggregator/config.py, setup.py, tests/test_config.py
Due to the kaptan library being unmaintained.
Supersedes #72
=> Drop support for other configuration file formats than yaml

git_aggregator/repo.py
With some repos, there is an issue when the origin url is changed to a fork in repo.yml.
Errors look like `unable to read sha1 file of`, `index-pack failed`
It's occuring when the remote is removed (git remote rm origin) then added back with another url (git remote add origin <new url>).
With this fix, we change the url inplace. `git remote set-url origin <new url>`
=> fix: git remote: change url instead of rm / add

git_aggregator/repo.py, tests/test_repo.py
git clone do not care if the dir exist or is empty
And an existing target_dir/.git is expected in the rest of this function
Without this patch, if the dir is empty, an error is triggered here just after:
https://github.com/acsone/git-aggregator/blob/master/git_aggregator/repo.py#L298
=> [fix] target_dir may be an empty directory

git_aggregator/repo.py
Very handy to be able to feed it with custom PRs info. Example: provide a parsed version of shell_after_commands containing PR patches.
=> [imp] repo.collect_prs_info allow to pass custom merges

README.rst
Add usage examples for Gitlab and Bitbucket repositories.
=> [DOC] Update README
